apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: apod-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: my-astronomia.com
      http:
        paths:
            - path: /
              backend:
               serviceName: apod-service
               servicePort: 80